apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-30T22:07:58Z"
  labels:
    app: hadwen
  name: hadwenweb
  namespace: default
spec:
  ports:
    - nodePort: 30175
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hadwen
    tier: web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 35.196.180.245
